# Generated by Django 4.1.3 on 2022-12-27 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('images', models.ImageField(default='default-news.img', upload_to='news_images', verbose_name='Изображение')),
                ('files', models.FileField(default='default-news.file', upload_to='news_files', verbose_name='Файл')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('athor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
