# Generated by Django 4.1.3 on 2023-01-02 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='like',
        ),
    ]
