# Generated by Django 4.1.3 on 2023-01-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='comment',
            field=models.IntegerField(default=0, verbose_name='Комментарии'),
        ),
    ]
