# Generated by Django 4.1.3 on 2023-01-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_news_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='idcom',
            field=models.CharField(default='1', max_length=1, verbose_name='idcom'),
        ),
    ]
