# Generated by Django 4.1.3 on 2023-01-06 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_comments_idcom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='idcom',
        ),
    ]
