# Generated by Django 4.1.3 on 2022-12-26 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('status', models.CharField(max_length=255, verbose_name='Статус')),
                ('phone', models.CharField(max_length=12, verbose_name='Фамилия')),
                ('yourself', models.TextField(verbose_name='О себе')),
                ('photo', models.ImageField(default='default-photo.png', upload_to='user_photo', verbose_name='Фото')),
                ('cover', models.ImageField(default='default-cover.png', upload_to='user_cover', verbose_name='Обложка')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
