# Generated by Django 4.1.3 on 2022-12-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Номер телефона'),
        ),
    ]
