# Generated by Django 4.1.3 on 2022-12-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(default=1, unique=True, verbose_name='Идентификатор'),
            preserve_default=False,
        ),
    ]
