# Generated by Django 4.1.3 on 2023-01-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='firstname',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
    ]
